# Research Question 1

Is perceived social support received from Facebook (FMSS) associated with lower rates of 

* Positive screens for psychiatric disorders
  * PC-PTSD
  * PHQ-2
  * AUDIT-C
* Positive screen for suicidality?
  * DSI-SS


## Unadjusted comparisons

```{r}
align <- "llccccc"
digits <- c(0, 0, 1, 0, 0, 0, 0)
means2Group("fmss", "indPTSD") %>% kable(align = align, digits = digits)
means2Group("fmss", "indPHQ") %>% kable(align = align, digits = digits)
means2Group("fmss", "indAuditC") %>% kable(align = align, digits = digits)
means2Group("fmss", "indDSISS") %>% kable(align = align, digits = digits)
```

```{r plot2Groups}
plot2Groups("fmss", "indPTSD", "FMSS", "PC-PTSD")
plot2Groups("fmss", "indPHQ", "FMSS", "PHQ-2")
plot2Groups("fmss", "indAuditC", "FMSS", "AUDIT-C")
plot2Groups("fmss", "indDSISS", "FMSS", "DSI-SS")
```


## Adjusted comparisons

```{r}
covar <- c("countSocialMediaExclFB",
           "comm_inperson",
           "indSuicideConsideredEver",
           "countSuicideAttempts")
```

Filter subjects with missing covariates.

```{r}
df <-
  df %>% 
  select_(.dots = c("record_id", covar)) %>% 
  na.omit() %>% 
  select(record_id) %>% 
  merge(., df, by = "record_id")
```


### PC-PTSD

```{r}
y <- "indPTSD"
fitModel(y) %>% .[["summary"]] %>% tidy() %>% kable(digits = 3)
M <- fitModel(y, covar)
M[["summary"]] %>% tidy() %>% kable(digits = 3)
M[["summary"]] %>% glance() %>% kable(digits = 3)
M[["plotResid"]]
```

### PHQ-2

```{r}
y <- "indPHQ"
fitModel(y) %>% .[["summary"]] %>% tidy() %>% kable(digits = 3)
M <- fitModel(y, covar)
M[["summary"]] %>% tidy() %>% kable(digits = 3)
M[["summary"]] %>% glance() %>% kable(digits = 3)
M[["plotResid"]]
```

### AUDIT-C

```{r}
y <- "indAuditC"
fitModel(y) %>% .[["summary"]] %>% tidy() %>% kable(digits = 3)
M <- fitModel(y, covar)
M[["summary"]] %>% tidy() %>% kable(digits = 3)
M[["summary"]] %>% glance() %>% kable(digits = 3)
M[["plotResid"]]
```

### DSI-SS

```{r}
y <- "indDSISS"
fitModel(y) %>% .[["summary"]] %>% tidy() %>% kable(digits = 3)
M <- fitModel(y, covar)
M[["summary"]] %>% tidy() %>% kable(digits = 3)
M[["summary"]] %>% glance() %>% kable(digits = 3)
M[["plotResid"]]
```
